name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  TAG: rasmus256docker/advent_of_code_day1_part1:$(date +%s)
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        tags: rasmus256docker/advent_of_code_day1_part1:$(date +%s)
    - uses: actions/checkout@v3
    - name: Docker Login
    # You may pin to the exact commit or the version.
    # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: rasmus256docker
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - run: |
        export FOO=$(date +%s)
        echo "::set-env name=FOO::$FOO"
    - name: Build and push day1_part1
      uses: docker/build-push-action@v3
      with:
        file: day1/part1/Dockerfile
        context: day1/part1
        push: true
        tags: ${{ steps.meta.outputs.tags }}
