name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  TAG: $(date +%s)
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:          
        images: rasmus256docker/advent_of_code_day1_part1
        tags: ${{env.TAG}}
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          d1p1:
            - 'day1/part1/*'
            
          d1p2:
            - 'day1/part2/*'
    - name: Docker Login
    # You may pin to the exact commit or the version.
    # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: rasmus256docker
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - 
      if: steps.filter.outputs.d1p1 == 'true'
      run: |
        export FOO=rasmus256docker/advent_of_code_day1_part1:$(date +%s)
        echo "::set-env name=FOO::$FOO"
    - 
      if: steps.filter.outputs.d1p1 == 'true'
      name: Build and push day1_part1
      uses: docker/build-push-action@v3
      with:
        file: day1/part1/Dockerfile
        context: day1/part1
        push: true
        tags: ${{ env.FOO }}
    - 
      if: steps.filter.outputs.d1p2 == 'true'
      run: |
        export FOO=rasmus256docker/advent_of_code_day1_part2:$(date +%s)
        echo "::set-env name=FOO::$FOO"
    - 
      if: steps.filter.outputs.d1p2 == 'true'
      name: Build and push day1_part2
      uses: docker/build-push-action@v3
      with:
        file: day1/part2/Dockerfile
        context: day1/part2
        push: true
        tags: ${{ env.FOO }}
