name: Docker Image CI

on:
  push:
    branches: [ "main" ]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  TAG: $(date +%s)
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo '::set-output name=value::[\"day1\", \"day2\"]'
  build:
    needs: [ setup ]
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    uses: Rasmus256/advent_of_code_2022/.github/workflows/template.yml@main
    with:
      day: ${{ matrix.value }}
      part: part1
      tag: $(date +%s)
    secrets: inherit
  day1_part2:
    uses: Rasmus256/advent_of_code_2022/.github/workflows/template.yml@main
    with:
      day: day1
      part: part2
      tag: $(date +%s)
    secrets: inherit
  day2_part2:
    uses: Rasmus256/advent_of_code_2022/.github/workflows/template.yml@main
    with:
      day: day2
      part: part2
      tag: $(date +%s)
    secrets: inherit
