name: Docker Image CI

on:
  push:
    branches: [ "main" ]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  TAG: $(date +%s)
jobs:
  day1_part1:
    uses: Rasmus256/advent_of_code_2022/.github/workflows/template.yml@main
    with:
      day: day1
      part: part1
      tag: $(date +%s)
    secrets: inherit
  day1_part2:
    uses: Rasmus256/advent_of_code_2022/.github/workflows/template.yml@main
    with:
      day: day1
      part: part2
      tag: $(date +%s)
    secrets: inherit
