name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
    # You may pin to the exact commit or the version.
    # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: rasmus256docker
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - run: |
        export FOO=$(date +%s)
        echo "::set-env name=FOO::$FOO"
    - name: Build the Docker image
      working-directory: day1/part1
      run: docker build . --file ./Dockerfile --tag my-image-name:$FOO 
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: day1/part1
        file: Dockerfile
        push: true
        tags: my-image-name:latest
