name: Docker Image CI

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches: [ "main" ]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix_p1: ${{ steps.matrix.outputs.value }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - id: matrix
        run: |
          echo '::set-output name=value::[{d: "2023/day8", p: "part1"}]'
      - id: tag
        run: |
          echo "::set-output name=tag::$(date +'%s')"
  build_image:
    needs: [ setup ]
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix_p1)}}
    uses: Rasmus256/advent_of_code/.github/workflows/template.yml@main
    with:
      day: ${{ matrix.value.d }}
      part: ${{ matrix.value.p }}
      tag: "2.1.${{github.run_number}}"
      push: "false"
    secrets: inherit
